server:
  port: 8089


spring:
  application:
    name: core-user-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

eureka:
  service-url:
    defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}


db:
  host: ${dbhost.report.service}
  username: ${dbuser.report.service}
  password: ${dbpassword.report.service}
  pool:
    maximum: ${dbmaxpool.report.service:10}
    minimum: ${dbminpool.report.service:3}
    idle: ${dbidlepool.report.service:10}
    life:
      time:
        max: ${dbmaxlifetimepool.report.service:1800000}
    leak:
      detect:
        threshold: ${dbleakdetectthreshold.report.service:0}
    connect:
      time:
        out: ${dbconnecttimeout.report.service:30000}
    keepAlive: ${dbkeepAlivepool.report.service:}800000
  driver:
    class:
      name: ${dbdriver.report.service}

kafka:
  schema:
    registry:
      url: ${kafka.schm.registry:http://schema-registry:8081}
  producer:
    ack: all
    linger: 5
    rto:
      ms: 60000
    retry:
      count: 5

compression:
  type: snappy